version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pbl_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=${MONGO_URI} 
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - ./backend/.env 
    volumes:
      - ./backend:/app
      - /app/__pycache__